# Generated by Django 4.2.16 on 2024-12-03 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkTraffic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.FloatField()),
                ('protocol_type', models.CharField(max_length=20)),
                ('service', models.CharField(max_length=50)),
                ('flag', models.CharField(max_length=10)),
                ('src_bytes', models.PositiveIntegerField()),
                ('dst_bytes', models.PositiveIntegerField()),
                ('land', models.BooleanField()),
                ('wrong_fragment', models.PositiveIntegerField()),
                ('urgent', models.PositiveIntegerField()),
                ('hot', models.PositiveIntegerField()),
                ('logged_in', models.BooleanField()),
                ('num_compromised', models.PositiveIntegerField()),
                ('count', models.PositiveIntegerField()),
                ('srv_count', models.PositiveIntegerField()),
                ('serror_rate', models.FloatField()),
                ('rerror_rate', models.FloatField()),
                ('same_srv_rate', models.FloatField()),
                ('diff_srv_rate', models.FloatField()),
                ('srv_diff_host_rate', models.FloatField()),
                ('dst_host_count', models.PositiveIntegerField()),
                ('dst_host_srv_count', models.PositiveIntegerField()),
                ('dst_host_same_srv_rate', models.FloatField()),
                ('dst_host_diff_srv_rate', models.FloatField()),
                ('attack', models.BooleanField()),
            ],
        ),
    ]
