# Generated by Django 4.2.16 on 2024-12-03 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_traffic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networktraffic',
            name='duration',
            field=models.IntegerField(blank=True),
        ),
    ]
